services:
  odoo:
    image: odoo:17.0

    container_name: odoo17

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8069:8069"

    volumes:
      - /home/joche/Proyectos/Odoo/Modulo_reserva_salas:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo

    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

  db:
    image: postgres:15

    container_name: postgress15

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-backups:/backups
    
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:

  odoo-data: